insert into ingredient (name, unit, vegetarian, vegan) values ('salt', 'GRAMS',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('pepper', 'GRAMS',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('onion', 'HALVES',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('garlic', 'CLOVES',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('eggs', 'NONE',true, false);
insert into ingredient (name, unit, vegetarian, vegan) values ('milk', 'MILLILITRES',true, false);
insert into ingredient (name, unit, vegetarian, vegan) values ('bell peppers', 'NONE',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('chicken breast', 'NONE',false, false);
insert into ingredient (name, unit, vegetarian, vegan) values ('black beans', 'TINS',true, true);
insert into ingredient (name, unit, vegetarian, vegan) values ('tomatoes', 'NONE', true, true);